In [180]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [181]:
df = pd.read_csv("/content/ecommerce_raw.csv")

In [182]:
df.head()

,Customer_ID,Age,Gender,City,Signup_Date,Order_Date,Product_Category,Product_Price,Quantity,Discount,Payment_Method,Delivery_Days,Customer_Rating,Returned,Order_Status
0,CUST1190,32.0,Female,Ahmedabad,2024-08-29,2025-06-18,Home & Kitchen,200.00,5,10.0,Cash on Delivery,9.0,3.8,0,Delivered
1,CUST1044,28.0,Female,Jaipur,2024-04-23,2025-01-02,Grocery,140.84,2,10.0,UPI,6.0,NaN,0,Delivered
2,CUST1161,47.0,Female,Patna,2025-03-10,2025-11-10,Grocery,50.00,1,20.0,Net Banking,6.0,3.1,0,Delivered
3,CUST1015,23.0,Male,Mumbai,2025-04-25,2026-01-13,Grocery,79.11,2,10.0,Net Banking,5.0,3.5,0,Delivered
4,CUST1241,35.0,Female,Bengaluru,2025-02-26,2025-05-30,Books,100.00,3,15.0,Cash on Delivery,4.0,4.7,0,Delivered

In [183]:
df.isnull().sum()

Customer_ID          0
Age                 35
Gender              25
City                20
Signup_Date          0
Order_Date           0
Product_Category     0
Product_Price        0
Quantity             0
Discount            30
Payment_Method      26
Delivery_Days       20
Customer_Rating     41
Returned             0
Order_Status         0
dtype: int64

In [184]:
# find the percentage of missing valiues
df.isnull().sum()/len(df)*100

Customer_ID         0.000000
Age                 3.431373
Gender              2.450980
City                1.960784
Signup_Date         0.000000
Order_Date          0.000000
Product_Category    0.000000
Product_Price       0.000000
Quantity            0.000000
Discount            2.941176
Payment_Method      2.549020
Delivery_Days       1.960784
Customer_Rating     4.019608
Returned            0.000000
Order_Status        0.000000
dtype: float64

In [185]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       1020 non-null   object
 1   Age               985 non-null    float64
 2   Gender            995 non-null    object
 3   City              1000 non-null   object
 4   Signup_Date       1020 non-null   object
 5   Order_Date        1020 non-null   object
 6   Product_Category  1020 non-null   object
 7   Product_Price     1020 non-null   float64
 8   Quantity          1020 non-null   int64
 9   Discount          990 non-null    float64
 10  Payment_Method    994 non-null    object
 11  Delivery_Days     1000 non-null   float64
 12  Customer_Rating   979 non-null    float64
 13  Returned          1020 non-null   int64
 14  Order_Status      1020 non-null   object
dtypes: float64(5), int64(2), object(8)
memory usage: 119.7+ KB

In [186]:
df.duplicated().sum()

np.int64(20)

In [187]:
#now we have to keep 1 data upper one and delete below
df.drop_duplicates(inplace=True)

In [188]:
df.duplicated().sum()

np.int64(0)

In [189]:
M_list = ['Male', 'male', 'M', 'MALE']

In [190]:
F_list = ['Female', 'female', 'F', 'FEMALE']

In [191]:
df['Gender'].unique()

array(['Female', 'Male', 'MALE', nan, 'FEMALE', 'male', 'F', 'M',
       'female'], dtype=object)

In [192]:
df[df['Gender'].isin(F_list)]['Gender'].value_counts()

Gender
Female    478
female     15
FEMALE     13
F          10
Name: count, dtype: int64

In [193]:
df[df['Gender'].isin(F_list)]['Gender'].replace(F_list, 'F')

0       F
1       F
2       F
4       F
8       F
       ..
1011    F
1013    F
1015    F
1016    F
1018    F
Name: Gender, Length: 516, dtype: object

In [194]:
df.loc[df['Gender'].isin(F_list), 'Gender'] = 'Female'
df.loc[df['Gender'].isin(M_list), 'Gender'] = 'Male'

In [195]:
df['Gender'].unique()

array(['Female', 'Male', nan], dtype=object)

In [196]:
df['Gender'] = df['Gender'].replace('nan', 'Unknown')

In [197]:
df['Gender'].unique()

array(['Female', 'Male', nan], dtype=object)

In [198]:
df.head()

,Customer_ID,Age,Gender,City,Signup_Date,Order_Date,Product_Category,Product_Price,Quantity,Discount,Payment_Method,Delivery_Days,Customer_Rating,Returned,Order_Status
0,CUST1190,32.0,Female,Ahmedabad,2024-08-29,2025-06-18,Home & Kitchen,200.00,5,10.0,Cash on Delivery,9.0,3.8,0,Delivered
1,CUST1044,28.0,Female,Jaipur,2024-04-23,2025-01-02,Grocery,140.84,2,10.0,UPI,6.0,NaN,0,Delivered
2,CUST1161,47.0,Female,Patna,2025-03-10,2025-11-10,Grocery,50.00,1,20.0,Net Banking,6.0,3.1,0,Delivered
3,CUST1015,23.0,Male,Mumbai,2025-04-25,2026-01-13,Grocery,79.11,2,10.0,Net Banking,5.0,3.5,0,Delivered
4,CUST1241,35.0,Female,Bengaluru,2025-02-26,2025-05-30,Books,100.00,3,15.0,Cash on Delivery,4.0,4.7,0,Delivered

In [199]:
df.shape

(1000, 15)

In [200]:
df['City'].unique()

array(['Ahmedabad', 'Jaipur', 'Patna', 'Mumbai ', 'Bengaluru',
       'Hyderabad', 'Mumbai', 'Chennai', 'Delhi', 'bengaluru', 'Kolkata',
       'Pune', 'delhi', 'mumbai', nan, 'jaipur', 'Jaipur ', 'Delhi ',
       'BANGALORE', 'PATNA', 'patna'], dtype=object)

In [201]:
df['City'] = df['City'].replace({
    'Mumbai ': 'Mumbai',
    'mumbai': 'Mumbai',
    'Bengaluru': 'Bengaluru',
    'bengaluru': 'Bengaluru',
    'BANGALORE': 'Bengaluru',
    'Patna': 'Patna',
    'PATNA': 'Patna',
    'patna': 'Patna',
    'Jaipur ': 'Jaipur',
    'jaipur': 'Jaipur',
    'Delhi ': 'Delhi',
    'delhi': 'Delhi'
})

In [202]:
df['City'].unique()

array(['Ahmedabad', 'Jaipur', 'Patna', 'Mumbai', 'Bengaluru', 'Hyderabad',
       'Chennai', 'Delhi', 'Kolkata', 'Pune', nan], dtype=object)

In [203]:
df['City'].fillna('Unknown', inplace=True)

/tmp/ipykernel_2305/1427820024.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna('Unknown', inplace=True)

In [204]:
df['Product_Category'].unique()

array(['Home & Kitchen', 'Grocery', 'Books', 'Clothes', 'Electronics',
       'Clothing', 'Beauty', 'beauty', 'home & kitchen', 'clothing',
       'electronics', 'Electronic', 'books', 'grocery',
       'Home and Kitchen'], dtype=object)

In [205]:
df['Product_Category'] = df['Product_Category'].replace({
    'home & kitchen': 'Home & Kitchen',
    'Home and Kitchen': 'Home & Kitchen',
    'electronics': 'Electronics',
    'Electronic': 'Electronics',
    'grocery': 'Beauty',
    'beauty': 'Patna',
    'Clothing': 'Clothes',
    'books' : 'Books',
    'clothing': 'Clothes'
})

In [206]:
df['Product_Category'].unique()

array(['Home & Kitchen', 'Grocery', 'Books', 'Clothes', 'Electronics',
       'Beauty', 'Patna'], dtype=object)

In [207]:
df['Age'].unique()

array([ 32.,  28.,  47.,  23.,  35.,  37.,  24.,  nan,  25.,  41.,  40.,
        38.,  29.,  46.,  39.,  34.,  33.,  30.,  19.,  42.,  18.,  26.,
        31.,  48.,  50.,  36.,  27.,  43.,  20.,  22.,  51.,  44.,  -1.,
        21.,  52.,  63.,  53.,  49.,  56.,  45., 120.,  54.,  -5., 150.,
        58.,  55.,  62.,  65.])

In [208]:
df['Age'].isna().sum()

np.int64(35)

In [209]:
#remove invalid age using reasonabe bussinus rule
df = df[(df['Age'].between(18, 65)) | (df['Age'].isna())]

In [210]:
#Handle the missing ages separately
df['Age'] = df['Age'].fillna(df['Age'].median())

In [211]:


print("Unique Age values after cleaning:")
print(df['Age'].unique())

print("\nMissing values after cleaning:")
print(df[['Age']].isnull().sum())

Unique Age values after cleaning:
[32. 28. 47. 23. 35. 37. 24. 25. 41. 40. 38. 29. 46. 39. 34. 33. 30. 19.
 42. 18. 26. 31. 48. 50. 36. 27. 43. 20. 22. 51. 44. 21. 52. 63. 53. 49.
 56. 45. 54. 58. 55. 62. 65.]

Missing values after cleaning:
Age    0
dtype: int64

In [212]:
df.drop(
    df[df['Product_Category'].isin([1.0, 5.0])].index,
    inplace=True
)

In [213]:
df['Quantity'].unique()

array([ 5,  2,  1,  3,  4, -2, -1,  0])

In [214]:
df[df['Quantity'] <= 0]

,Customer_ID,Age,Gender,City,Signup_Date,Order_Date,Product_Category,Product_Price,Quantity,Discount,Payment_Method,Delivery_Days,Customer_Rating,Returned,Order_Status
24,CUST1065,30.0,Male,Chennai,2025-01-26,2025-02-12,Grocery,54.74,-2,30.0,Net Banking,6.0,5.0,0,Delivered
133,CUST1091,24.0,Male,Hyderabad,2024-01-19,2024-04-27,Grocery,187.10,-1,25.0,UPI,3.0,4.8,0,Delivered
242,CUST1108,19.0,Female,Jaipur,2024-08-08,2024-08-28,Home & Kitchen,330.39,-1,10.0,Credit Card,5.0,4.0,0,Delivered
328,CUST1094,36.0,Male,Ahmedabad,2024-03-20,2025-01-05,Electronics,855.32,0,15.0,Net Banking,6.0,4.3,1,Returned
391,CUST1248,32.0,Male,Pune,2024-10-02,2025-08-10,Beauty,393.76,-2,20.0,Cash on Delivery,8.0,3.3,0,Delivered
460,CUST1197,47.0,Male,Mumbai,2024-05-07,2024-12-30,Clothes,300.00,-1,10.0,Debit Card,4.0,5.0,0,Delivered
524,CUST1115,20.0,Male,Bengaluru,2024-08-21,2025-05-28,Electronics,387.19,-2,20.0,Credit Card,4.0,3.9,0,Delivered
566,CUST1097,40.0,Female,Delhi,2024-07-21,2024-08-13,Beauty,190.70,-2,25.0,Debit Card,8.0,4.6,0,Delivered

In [215]:
df = df[df['Quantity'] > 0].copy()

In [216]:
df['Quantity'].unique()

array([5, 2, 1, 3, 4])

In [217]:
df['Product_Price'].unique()

array([ 2.00000e+02,  1.40840e+02,  5.00000e+01,  7.91100e+01,
        1.00000e+02,  2.83600e+02,  2.61430e+02,  2.86330e+02,
        1.26960e+02,  3.74770e+02,  5.12210e+02,  5.53310e+02,
        7.38110e+02,  1.91920e+02,  7.20220e+02,  2.94220e+02,
        1.50000e+02,  6.00000e+04,  1.05550e+02,  6.67760e+02,
        9.69500e+01,  2.47940e+02,  5.50900e+01,  3.33770e+02,
        1.54200e+02,  3.32060e+02,  3.64650e+02,  3.00000e+02,
        2.04570e+02,  6.30920e+02,  8.32080e+02,  7.86100e+01,
        1.12373e+03,  5.90820e+02,  3.21710e+02,  3.75620e+02,
        9.05470e+02,  2.19520e+02,  3.28510e+02,  1.16000e+02,
        2.07450e+02,  1.73270e+02,  3.33050e+02,  7.22910e+02,
        5.81100e+02,  4.47980e+02,  6.33690e+02,  5.63070e+02,
        2.45480e+02,  3.49450e+02,  1.48050e+03,  1.53680e+02,
        8.45910e+02,  1.12620e+02,  2.76190e+02,  7.26500e+01,
        4.18910e+02,  4.65770e+02,  3.69700e+02,  3.04320e+02,
        1.97200e+02,  4.34240e+02,  9.41500e+01,  5.03490e+02,
        2.17780e+02,  4.50000e+04,  9.78420e+02,  5.80190e+02,
        1.08900e+02,  1.94860e+02,  1.90630e+02,  2.95820e+02,
        1.00620e+02,  3.45620e+02,  4.40160e+02,  2.05650e+02,
        4.01030e+02,  2.55060e+02,  6.22900e+01,  1.86690e+02,
        2.04200e+02,  5.06600e+01,  6.77070e+02,  1.48730e+02,
        3.38030e+02,  1.40270e+02,  1.99660e+02,  2.47260e+02,
        1.56940e+02,  5.07120e+02,  1.17640e+02,  1.13560e+02,
        1.02610e+02,  9.79170e+02,  3.41830e+02,  4.01180e+02,
        4.14600e+02,  6.25680e+02,  8.25700e+01,  1.54780e+02,
        1.29770e+02,  4.74810e+02,  2.09640e+02,  2.41900e+02,
        3.30890e+02,  3.44610e+02,  1.09600e+02,  1.14610e+02,
        1.75960e+02,  1.06460e+02,  1.37660e+02,  1.35110e+02,
        1.38820e+02,  3.07690e+02,  1.59890e+02,  1.34950e+02,
        6.82140e+02,  3.92480e+02,  3.31160e+02,  2.29240e+02,
        3.39140e+02,  8.10900e+02,  3.32130e+02,  2.97860e+02,
        3.06970e+02,  2.39980e+02,  1.96630e+02,  2.38280e+02,
        3.35890e+02,  7.83300e+01,  1.45820e+02,  3.29880e+02,
        1.82790e+02,  1.59240e+02,  3.08480e+02,  3.79590e+02,
        5.47670e+02,  6.82990e+02, -1.00000e+02,  2.29840e+02,
        1.41660e+02,  9.12500e+02,  4.65350e+02,  1.28470e+02,
        1.37615e+03,  1.08600e+02,  2.51380e+02,  1.34750e+02,
        2.74970e+02,  2.09690e+02,  1.31190e+02,  2.48990e+02,
        3.89410e+02,  3.22500e+02,  3.75220e+02,  4.01970e+02,
        2.78070e+02,  1.24340e+02,  6.42360e+02,  2.02770e+02,
        4.60220e+02,  2.98990e+02,  2.58440e+02,  1.04680e+02,
        3.67070e+02,  8.47400e+01,  2.73730e+02,  3.34820e+02,
        0.00000e+00,  1.28960e+02,  1.60110e+02,  2.41800e+02,
        2.63330e+02,  2.46710e+02,  8.15910e+02,  4.85850e+02,
        3.66020e+02,  2.52960e+02,  2.08980e+02,  7.59560e+02,
        1.02520e+02,  3.35490e+02,  5.46790e+02,  5.75750e+02,
        4.97030e+02,  5.63060e+02,  3.42030e+02,  6.25700e+01,
        2.12930e+02,  5.91600e+01,  1.90390e+02,  2.71460e+02,
        8.79500e+01,  7.75300e+01,  5.99220e+02,  8.96210e+02,
        4.63910e+02,  1.65620e+02,  6.33100e+01,  2.29720e+02,
        1.54760e+02,  1.17460e+02,  1.58670e+02,  4.46400e+02,
        1.43450e+02,  1.77360e+02,  1.79790e+02,  2.06490e+02,
        4.43300e+02,  2.29500e+02,  1.27860e+02,  4.02630e+02,
        1.62570e+02,  1.58060e+02,  5.64700e+01,  1.46280e+02,
        2.51400e+02,  8.01200e+01,  3.61160e+02,  5.19130e+02,
        3.82350e+02,  1.35600e+02,  2.37320e+02,  3.46300e+02,
        3.11550e+02,  4.02280e+02,  4.40560e+02,  1.33750e+02,
        6.96480e+02,  3.26420e+02,  5.05460e+02,  2.35090e+02,
        1.99370e+02,  2.27100e+02,  3.74740e+02,  8.87000e+01,
       -5.00000e+02,  2.06590e+02,  3.09290e+02,  1.41746e+03,
        1.90370e+02,  2.51140e+02,  8.91070e+02,  1.16220e+02,
        1.75330e+02,  9.83300e+01,  4.10910e+02,  3.23180e+02,
        2.86930e+02,  6.43850e+02,  8.58500e+01,  2.52340e+02,
        5.09810e+02,  4.03790e+02,  1.70561e+03,  6.54020e+02,
        1.59580e+02,  4.69030e+02,  3.38280e+02,  6.66320e+02,
        1.62340e+02,  1.56450e+02,  2.00430e+02,  1.72810e+02,
        1.56100e+02,  1.58360e+02,  3.72450e+02,  6.85800e+01,
        2.69200e+02,  4.39790e+02,  1.20577e+03,  4.08430e+02,
        3.45480e+02,  3.63330e+02,  1.61710e+02,  9.54500e+01,
        1.85570e+02,  2.18850e+02,  5.31600e+02,  4.24560e+02,
        8.55800e+01,  2.29620e+02,  9.58100e+01,  1.32740e+02,
        1.34483e+03,  5.74190e+02,  2.19470e+02,  1.20920e+02,
        8.62840e+02,  8.41260e+02,  2.05900e+02,  3.97850e+02,
        3.20170e+02,  6.37220e+02,  3.04600e+02,  5.12700e+01,
        2.57490e+02,  6.77320e+02,  7.26100e+01,  2.53390e+02,
        7.69710e+02,  4.71530e+02,  3.32100e+02,  3.82110e+02,
        5.71300e+01,  2.43510e+02,  1.51700e+02,  1.80770e+02,
        3.47280e+02,  1.10550e+02,  2.46830e+02,  1.49640e+02,
        2.29280e+02,  1.34340e+02,  2.80960e+02,  2.48730e+02,
        4.05210e+02,  2.74880e+02,  2.45050e+02,  2.64930e+02,
        1.14880e+02,  1.83490e+02,  3.11520e+02,  4.14560e+02,
        6.75800e+01,  2.57130e+02,  4.12100e+02,  2.46490e+02,
        3.12700e+02,  7.05940e+02,  3.56630e+02,  4.42780e+02,
        5.83010e+02,  5.82860e+02,  7.50000e+04,  1.04370e+02,
        1.86740e+02,  2.92130e+02,  1.15580e+02,  2.18100e+02,
        2.16280e+02,  5.55900e+02,  1.15940e+03,  1.05530e+02,
        1.23120e+02,  1.12340e+02,  7.04930e+02,  4.85830e+02,
        1.53820e+02,  5.49510e+02,  1.64320e+02,  2.31460e+02,
        1.96910e+02,  9.20550e+02,  4.03100e+02,  3.02140e+02,
        2.50720e+02,  4.73690e+02,  1.07450e+02,  2.19010e+02,
        2.13640e+02,  1.06214e+03,  3.47900e+02,  3.40220e+02,
        6.01400e+01,  3.25780e+02,  2.90120e+02,  4.09670e+02,
        5.19760e+02,  3.39670e+02,  1.80330e+02,  2.51720e+02,
        8.78800e+01,  3.91410e+02,  2.70490e+02,  1.04600e+02,
        6.92400e+01,  1.69580e+02,  2.25430e+02,  7.16380e+02,
        2.14080e+02,  3.62620e+02,  1.80460e+02,  3.30410e+02,
        1.74200e+02,  4.05530e+02,  2.38700e+02,  1.60333e+03,
        5.95080e+02,  4.48680e+02,  1.77600e+02,  2.62000e+02,
        3.28120e+02,  3.57240e+02,  1.32970e+02,  3.07560e+02,
        2.37670e+02,  3.79770e+02,  3.17290e+02,  9.93100e+01,
        6.43780e+02,  1.55470e+02,  1.59660e+02,  9.81400e+01,
        1.32420e+02,  3.29220e+02,  5.45630e+02,  5.59570e+02,
        4.49550e+02,  3.11610e+02,  4.84420e+02,  1.26760e+02,
        7.29640e+02,  1.19900e+02,  1.52570e+02,  2.63900e+02,
        4.43780e+02,  6.99980e+02,  1.84810e+02,  2.59110e+02,
        1.66350e+02,  7.92100e+02,  2.36260e+02,  5.27800e+02,
        4.25380e+02,  6.51690e+02,  2.51090e+02,  3.26760e+02,
        2.39550e+02,  1.23070e+02,  4.16670e+02,  5.62940e+02,
        7.93220e+02,  1.02040e+02,  1.96290e+02,  1.35820e+02,
        3.01930e+02,  2.58290e+02,  5.44930e+02,  1.55790e+02,
        1.05440e+02,  2.28900e+02,  5.67470e+02,  4.72770e+02,
        2.31300e+02,  2.49490e+02,  1.08110e+02,  1.58240e+02,
        1.97410e+02,  1.42790e+02,  3.41780e+02,  1.57830e+02,
        2.71050e+02,  2.98010e+02,  6.63500e+01,  3.48570e+02,
        1.52190e+02,  1.85610e+02,  8.25100e+01,  2.44970e+02,
        6.11670e+02,  4.17480e+02,  1.66920e+02,  4.24800e+02,
        2.61890e+02,  6.35320e+02,  1.95050e+02,  1.19149e+03,
        3.59200e+02,  8.40400e+01,  5.34300e+01,  6.72840e+02,
        3.58230e+02,  1.58320e+02,  9.67160e+02,  2.52870e+02,
        8.88700e+01,  2.05320e+02,  2.34560e+02,  2.35240e+02,
        1.52100e+02,  2.41350e+02,  4.28620e+02,  3.47080e+02,
        1.26595e+03,  1.75980e+02,  1.17030e+02,  4.25030e+02,
        2.64270e+02,  1.64000e+02,  4.16620e+02,  8.54320e+02,
        2.80980e+02,  2.81700e+02,  2.31130e+02,  1.28940e+02,
        4.10040e+02,  1.32110e+02,  9.25900e+01,  2.72470e+02,
        7.71800e+01,  4.99920e+02,  2.21070e+02,  4.53850e+02,
        3.46140e+02,  6.63100e+01,  5.40180e+02,  5.75000e+02,
        1.53960e+02,  2.82530e+02,  2.04890e+02,  9.53110e+02,
        3.71830e+02,  3.70010e+02,  1.08730e+02,  1.50660e+02,
        9.78440e+02,  6.30000e+01,  5.37700e+02,  3.74220e+02,
        3.82090e+02,  5.45360e+02,  7.12690e+02,  3.27030e+02,
        7.09650e+02,  5.01400e+01,  3.54500e+02,  3.08720e+02,
        7.93500e+01,  5.66240e+02,  3.11370e+02,  4.49480e+02,
        4.37910e+02,  6.49150e+02,  2.78970e+02,  1.20610e+02,
        1.63680e+02,  5.66980e+02,  3.51080e+02,  5.78290e+02,
        3.55510e+02,  3.16010e+02,  2.52660e+02,  4.13820e+02,
        1.13810e+02,  1.20220e+02,  3.33780e+02,  5.10790e+02,
        3.33760e+02,  1.54790e+02,  8.81900e+01,  2.19640e+02])

In [218]:
df[df['Product_Price'] <= 0]

,Customer_ID,Age,Gender,City,Signup_Date,Order_Date,Product_Category,Product_Price,Quantity,Discount,Payment_Method,Delivery_Days,Customer_Rating,Returned,Order_Status
243,CUST1150,48.0,Male,Unknown,2024-10-02,2025-03-07,Beauty,-100.0,1,10.0,UPI,NaN,5.0,0,Delivered
295,CUST1121,30.0,Female,Mumbai,2024-03-15,2024-11-12,Electronics,0.0,4,25.0,Cash on Delivery,4.0,2.3,0,Delivered
393,CUST1098,33.0,Female,Ahmedabad,2024-10-30,2025-01-03,Grocery,0.0,1,0.0,Net Banking,1.0,4.3,0,Delivered
415,CUST1182,18.0,Male,Hyderabad,2025-04-27,2025-08-24,Clothes,-500.0,2,5.0,Debit Card,3.0,4.5,0,Delivered
437,CUST1237,33.0,Male,Jaipur,2024-08-20,2024-09-28,Electronics,0.0,1,NaN,Net Banking,5.0,2.4,0,Delivered
474,CUST1086,42.0,Female,Delhi,2025-02-08,2025-07-03,Beauty,-500.0,4,10.0,Debit Card,NaN,4.1,0,Delivered
508,CUST1071,23.0,Male,Kolkata,2024-03-06,2024-08-22,Electronics,-500.0,2,20.0,Net Banking,6.0,4.3,0,Delivered
762,CUST1106,26.0,Female,Delhi,2024-03-21,2024-08-17,Home & Kitchen,-100.0,2,10.0,Cash on Delivery,3.0,4.4,0,Delivered

In [219]:
#find invalid product price & quantity and clean data....also explain our treatment
df = df[df['Product_Price'] > 0].copy()

In [220]:
print("Minimum Quantity:", df['Quantity'].min())
print("Minimum Product Price:", df['Product_Price'].min())

Minimum Quantity: 1
Minimum Product Price: 50.0

In [221]:
df['Customer_Rating'].unique()

array([ 3.8,  nan,  3.1,  3.5,  4.7,  3.9,  3.3,  4.1,  5. ,  4.8,  4.5,
        4.3,  3.4,  4.2,  4. ,  2.8,  4.4,  3.6,  3.7,  4.9,  3.2,  4.6,
        0. ,  7. ,  3. , -1. ,  2.9,  2.7,  2.3,  2.6,  2.5])

In [222]:
df[(df['Customer_Rating'] < 1) | (df['Customer_Rating'] > 5)]

,Customer_ID,Age,Gender,City,Signup_Date,Order_Date,Product_Category,Product_Price,Quantity,Discount,Payment_Method,Delivery_Days,Customer_Rating,Returned,Order_Status
69,CUST1176,29.0,Female,Hyderabad,2025-01-09,2025-01-30,Clothes,300.00,3,20.0,Debit Card,4.0,0.0,0,Delivered
90,CUST1237,36.0,Male,Delhi,2024-06-12,2025-06-03,Clothes,300.00,1,30.0,Net Banking,1.0,7.0,0,Delivered
137,CUST1039,40.0,Male,Pune,2024-12-25,2025-11-15,Books,186.69,1,20.0,Cash on Delivery,3.0,-1.0,0,Delivered
154,CUST1172,29.0,Female,Ahmedabad,2024-08-20,2024-09-25,Beauty,247.26,5,15.0,Net Banking,5.0,7.0,0,Delivered
413,CUST1096,30.0,Female,Patna,2024-04-20,2024-11-25,Home & Kitchen,200.00,1,25.0,Credit Card,3.0,7.0,0,Delivered
626,CUST1191,44.0,Female,Delhi,2024-01-24,2024-02-16,Beauty,150.00,1,10.0,Debit Card,1.0,-1.0,0,Cancelled
931,CUST1158,33.0,Female,Patna,2024-12-05,2025-03-30,Grocery,153.96,3,NaN,Net Banking,4.0,7.0,0,Delivered
1003,CUST1201,28.0,Male,Kolkata,2024-07-19,2025-05-10,Electronics,355.51,1,0.0,Cash on Delivery,8.0,7.0,0,Delivered

In [223]:
df['Customer_Rating'].between(1, 5).all()

np.False_

In [224]:
df['Customer_Rating'] = df['Customer_Rating'].fillna(
    df['Customer_Rating'].median()
)

In [225]:
df['Customer_Rating'].unique()

array([ 3.8,  4.4,  3.1,  3.5,  4.7,  3.9,  3.3,  4.1,  5. ,  4.8,  4.5,
        4.3,  3.4,  4.2,  4. ,  2.8,  3.6,  3.7,  4.9,  3.2,  4.6,  0. ,
        7. ,  3. , -1. ,  2.9,  2.7,  2.3,  2.6,  2.5])

### Cleaning `Payment_Method`

To effectively clean the `Payment_Method` column, we first need to understand the variety and consistency of its entries. This step involves examining all unique values to identify any inconsistencies, misspellings, or variations that might need standardization.

In [ ]:
print("Unique Payment_Method values before cleaning:")
print(df['Payment_Method'].unique())

Unique Payment_Method values before cleaning:
['Cash on Delivery' 'UPI' 'Net Banking' 'Credit Card' 'Debit Card' nan 1.0
 5.0]